# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oppo/msm8974-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter bacon find7 n3,$(TARGET_DEVICE)),)

endif
